#! /bin/sh
#
# Installation du module networkx
# Par defaut dans : $CASSIOPEE/Dist/bin/$ELSAPROD/
# Sinon : dans le repertoire specifie en argument
#
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in you environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    if [ "$ELSAPROD" = "" ]; then
        echo "You must specify a ELSAPROD in your environment."
        echo "This variable identifies the processor type."
        exit
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or-'
    echo 'install <dir>: install in directory <dir>.'
    exit
fi

# installation
python3 setup.py install --prefix="$INSTALLPATH"

# Test installation
# kpython -n 2 -t 1 test/t1.py

echo "Testing Mpi4py installation with mpirun..."

mpirun --version

mpirun -n 2 python3 test/t1.py

# Check if mpirun was successful
if [ $? -ne 0 ]; then
    echo "Mpi4py test failed. Aborting."
    exit 1
fi

echo "Mpi4py correctly installed."