#!/bin/sh

MODULES='KCore Mpi4py Converter Geom Transform Generator Post Initiator XCore Connector Distributor2 CPlot Dist2Walls RigidMotion Compressor Intersector'

export OMP_NUM_THREADS=$(grep -c ^processor /proc/cpuinfo)
echo "Number of processors (OMP_NUM_THREADS): $OMP_NUM_THREADS"

# Function to compile a module
compile_module() {
    module=$1
    should_clean_build=$2
    cd "$CASSIOPEE/../$module"

    if [ "$should_clean_build" = "clean" ] && [ -d "./build/" ]; then
        echo "Removing existing build directory for $PWD/build/"
        rm -rf ./build/
    fi

    if [ ! -x install ]; then
        echo "Changing permissions of install script for $module"
        chmod +x install
    fi

    # Redirect the output of the install script to the log file
    actual_log_file="../${module}.log"
    ./install >> "$actual_log_file" 2>&1
    install_status=$?

    if [ $install_status -ne 0 ] && [ "$should_clean_build" != "clean" ]; then
        echo "Installation failed."
        tail -20 "$actual_log_file" | awk '{print "\033[31m" $0 "\033[39m"}'
        exit 1
    # elif [ $install_status -ne 0 ] && [ "$should_clean_build" = "clean" ]; then
    #     tail -2 "$actual_log_file" | awk '{print "\033[31m" $0 "\033[39m"}'
    else
        tail -1 "$actual_log_file" | awk '{print "\033[32m" $0 "\033[39m"}'
    fi
}

# Clean up the build environment
echo "Cleaning up the build environment"
./clean

# Compile KCore first, which should fail before sourcing the environment
echo "Pre-compiling module KCore"
compile_module "KCore" "clean"

# Source the environment script for Cassiopee
. $CASSIOPEE/Dist/env_Cassiopee.sh

# Compile the rest of the modules
total_modules=$(echo $MODULES | wc -w)
current_module=1

for module in $MODULES
do
    echo "Compiling module $current_module of $total_modules in $module.log"
    if [ "$module" = "KCore" ]; then
        # Compile KCore again after sourcing the environment
        compile_module "KCore" "noclean"
    else 
        compile_module "$module" "clean"
    fi
    current_module=$((current_module+1))
done

chmod +x $CASSIOPEE/Dist/bin/x86_r8/lib/../cassiopee
